version: "3"

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    expose:
      - "6379:6379"
