version: "3"

services:
  postgres:
    container_name: dev-postgres
    build: ./postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres_user_123456789"
      POSTGRES_PASSWORD: "password_123456789"
