version: "3"

services:
  redis:
    build: .
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./backups:/backups
    command: redis-server /usr/local/etc/redis/redis.conf

  backup:
    image: alpine
    volumes:
      - ./backups:/backups
      - ./backup.sh:/backup.sh
    command: sh -c "chmod +x /backup.sh && crond -f -d 8"
    depends_on:
      - redis
