version: "3.8"

services:
  cosmosdb:
    restart: always
    container_name: "azure-cosmosdb-emulator"
    hostname: "azurecosmosemulator"
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
    mem_limit: 4GB
    tty: true
    ports:
      - "8081:8081" # 起動から3分後くらいに https://localhost:8081/_explorer/index.html
      - "8900:8900"
      - "8901:8901"
      - "8902:8902"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
      - "10256:10256"
      - "10350:10350"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./data/azurite:/data

  init-cosmosdb:
    build: .
    depends_on:
      - cosmosdb
